### ISSUE TITLE
karma only for people present in channel

### ISSUE THREAD

**Issue by LeSpocky** [netz39/hal39#11]
Without protection one could give karma to anyone, even to quite similar looking entities:

```
Fr|21:52:53 < _MrTux_> tux++
Fr|21:52:54 < hal39> tux is on the rise! (Karma: 2)
Fr|21:53:07 < _MrTux_> tux++
Fr|21:53:07 < hal39> tux is on the rise! (Karma: 3)
Fr|21:53:09 < _MrTux_> tux++
Fr|21:53:09 < hal39> tux +1! (Karma: 4)
Fr|21:53:10 < _MrTux_> tux++
Fr|21:53:11 < hal39> tux leveled up! (Karma: 5)
Fr|21:53:18 < _MrTux_> _MrTux_+
Fr|21:53:22 < _MrTux_> _MrTux_++
Fr|21:53:22 < hal39> Hey everyone! _MrTux_ is a narcissist!
Fr|21:53:26 < _MrTux_> *lol*
Fr|21:53:33 < _MrTux_> tux--
Fr|21:53:34 < hal39> tux lost a life. (Karma: 4)
Fr|21:53:35 < _MrTux_> tux--
Fr|21:53:35 < hal39> tux took a hit! Ouch. (Karma: 3)
Fr|21:53:37 < _MrTux_> tux--
Fr|21:53:38 < hal39> tux took a hit! Ouch. (Karma: 2)
Fr|21:53:39 < _MrTux_> tux--
Fr|21:53:39 < hal39> tux took a dive. (Karma: 1)
```

I guess it would be good to have some kind of filter so karma is only applied to people present in channel. This could of course be circumvented by giving oneself another nick, but it would prevent easy trolling.

**Comment by apfohl** [comment]
But what if I want to give karma to a thing?

**Comment by LeSpocky** [comment]
Karma is a concept for living entities. Why give it to a thing?

**Comment by apfohl** [comment]
This script is only for fun. The karmas make no clear statement about something. In my oppinion we should let us give karma to our 3d printer because of its awesomeness.
